import 'package:hive_flutter/hive_flutter.dart';
import '../models/clinical_log.dart';

class HiveService {
  static const String _boxName = 'clinicalLogsBox';

  /// Initialize Hive and register adapters
  static Future<void> init() async {
    await Hive.initFlutter();

    // Register adapters - these are generated by hive_generator
    if (!Hive.isAdapterRegistered(ClinicalLogEntryAdapter().typeId)) {
      Hive.registerAdapter(ClinicalLogEntryAdapter());
    }
    if (!Hive.isAdapterRegistered(RiskLevelAdapter().typeId)) {
      Hive.registerAdapter(RiskLevelAdapter());
    }
    if (!Hive.isAdapterRegistered(LogStatusAdapter().typeId)) {
      Hive.registerAdapter(LogStatusAdapter());
    }

    // Open the box
    await Hive.openBox<ClinicalLogEntry>(_boxName);
  }

  /// Get the Hive box for clinical logs
  static Box<ClinicalLogEntry> _getBox() {
    return Hive.box<ClinicalLogEntry>(_boxName);
  }

  /// Save a clinical log entry to Hive
  static Future<void> saveLog(ClinicalLogEntry entry) async {
    final box = _getBox();
    await box.put(entry.id, entry);
  }

  /// Get all clinical log entries from Hive
  static Future<List<ClinicalLogEntry>> getAllLogs() async {
    final box = _getBox();
    return box.values.toList();
  }

  /// Get a specific clinical log entry by ID
  static Future<ClinicalLogEntry?> getLog(String id) async {
    final box = _getBox();
    return box.get(id);
  }

  /// Delete a clinical log entry by ID
  static Future<void> deleteLog(String id) async {
    final box = _getBox();
    await box.delete(id);
  }

  /// Delete all clinical log entries
  static Future<void> deleteAllLogs() async {
    final box = _getBox();
    await box.clear();
  }

  /// Get count of clinical log entries
  static Future<int> getLogCount() async {
    final box = _getBox();
    return box.length;
  }
}